src/blogs/urls.py
from django.conf.urls import url

from . import views
from django.views import generic

app_name = 'blogs'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.BlogView.as_view(), name='detail'),
]

src/stackoverflow/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('login.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('textform.urls')),
    url(r'^search/', include('haystack.urls', app_name='search', namespace='search')),
]

src/textform/urls.py
from django.conf.urls import url, include
from . import views
import comments.views
import comments.urls

app_name = 'textform'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^deletemessage/(?P<pk>[0-9]+)$', views.deletemessage, name='deletemessage'),
    url(r'^editmessage/(?P<pk>.+)$', views.EditMessageView.as_view(), name='editmessage'),
    url(r'^newmessage$', views.NewMessageView.as_view(), name='newmessage'),
    url(r'^(?P<pk>[0-9]+)$', views.MessageView.as_view(), name='detail'),
    url(r'^comments/', include('comments.urls', namespace="comments")),
    url(r'^blogs/', include('blogs.urls', namespace="blogs")),
    url(r'^upmessage/$', views.upmessage, name="upmessage"),
]

src/comments/models.py
# coding: utf-8

from __future__ import unicode_literals
import datetime
from django.utils import timezone
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from textform.models import Message
from django.contrib.auth.models import User
from login.models import UserProfile
from django.dispatch import receiver
from .tasks import send_email_notification

@python_2_unicode_compatible
class Comment(models.Model):
    PUBLISH_OPTIONS = (
        ('y', 'yes'),
        ('n', 'no'),
    )

    message = models.ForeignKey(Message, null=True, blank=True, on_delete=models.CASCADE)
    text = models.TextField(verbose_name=u'Текст комментария')
    author = models.ForeignKey(User, null=True, blank=True, verbose_name=u'Автор комментария')
    pub_date = models.DateTimeField(verbose_name=u'Дата создания комментария', auto_now_add=True)
    is_published = models.CharField(max_length=1, choices=PUBLISH_OPTIONS)

    def __str__(self):
        return self.text

    def comment_beginning(self):
        return self.text[:20]


@receiver(models.signals.post_save, sender=Comment)
def on_comment_creation(sender, instance, *args, **kwargs):
    if kwargs.get('created'):
        comment = instance
        send_email_notification.delay(
            'gaintseva@phystech.edu',
            'New comment on question "{}"'.format(comment.message.title),
            'You got comment with the text: "{}"'.format(comment.text)
        )

src/textform/models.py
# coding: utf-8

from __future__ import unicode_literals
import datetime
from django.utils import timezone
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from login.models import UserProfile
from blogs.models import Blog


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=10)

    class Meta:
        verbose_name = u'Тэг'
        verbose_name_plural = u'Тэги'
        ordering = ('name',)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'Заголовок поста', default='none')
    text = models.TextField(verbose_name=u'Текст поста')
    author = models.ForeignKey(User, null=True, blank=True, verbose_name=u'Автор поста')

    answer_count = models.IntegerField(null=True, blank=True, verbose_name=u'Количество комментариев')
    like_count = models.IntegerField(null=True, blank=True, verbose_name=u'Количество лайков', default=0)
    rating = models.IntegerField(default=0)

    pub_date = models.DateTimeField(verbose_name=u'Дата создания поста', auto_now_add=True)
    mod_date = models.DateTimeField(verbose_name=u'Дата последней модификации', auto_now=True)

    blog = models.ForeignKey(Blog, null=True, blank=True, verbose_name=u'Блог', on_delete=models.CASCADE)

    published = models.BooleanField(default=True)

    tags = models.ManyToManyField(Tag, related_name='messages')
	
    def __str__(self):
        return self.text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def message_beginning(self):
        return self.text[:150]

src/textform/forms.py
from .models import Tag, Message
from django import forms
from django.core.exceptions import ValidationError

class IndexForm(forms.Form):
    search = forms.CharField(required=False)

    SORT_CHOICES = (('title', 'post title'), ('author', 'post author'), ('-pub_date', 'publication date'), ('-comments_count', 'rating'))
    sort = forms.ChoiceField(choices=SORT_CHOICES, label='Sort parameter', initial='author', widget=forms.Select(), required=False)

class MessageForm(forms.ModelForm):
    max_tag_number = 3
    class Meta:
        model = Message
        fields = ('title', 'text', 'blog', 'tags')

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        if tags and tags.count() > self.max_tag_number:
            raise ValidationError('Maximum %(self.max_tag_number)s categories are allowed.', code='invalid',)

        return tags

src/textform/views.py
from django.shortcuts import get_object_or_404, resolve_url
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template import RequestContext
from django.db.models import Q
from django.views import generic
from .models import Message
from .forms import IndexForm, MessageForm
from comments.models import Comment
from django.db.models import Count
from urllib2 import HTTPError
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError

class IndexView(generic.ListView):
    template_name = 'textform/index.html'
    context_object_name = 'latest_message_list'
    fields = ('author', 'title', 'text', 'blog', 'tags')
    model = Message

    def dispatch(self, request, *args, **kwargs):

        self.form = IndexForm(request.GET)
        self.form.is_valid()

        self.search_field = self.form.cleaned_data.get('search')
        self.sort_field = self.form.cleaned_data.get('sort')

        return super(IndexView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = self.form
        context['latest_comments'] = Comment.objects.order_by('-pub_date')[:7]
        return context

    def get_queryset(self):
        if self.request.user.is_authenticated():
            messages = Message.objects.filter(Q(published=True) | Q(author=self.request.user)) \
                .order_by('-pub_date').order_by('published')
        else:
            messages = Message.objects.filter(Q(published=True)).order_by('-pub_date')

        if self.search_field:
            messages = messages.filter(Q(title__icontains=self.search_field) | Q(text__icontains=self.search_field))

        messages = messages.annotate(comments_count=Count('comment__id'))
        if self.sort_field:
            messages = messages.order_by(self.sort_field)
        return messages



class MessageView(generic.CreateView):
    template_name = 'textform/detail.html'
    model = Comment
    fields = ('text',)
    context_object_name = 'comment'

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.message = get_object_or_404(Message.objects.all(), pk=pk)
        return super(MessageView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.message = self.message
        form.instance.author = self.request.user
        return super(MessageView, self).form_valid(form)

    def get_success_url(self):
        return resolve_url("textform:detail", pk=self.message.id)

    def get_context_data(self, **kwargs):
        context = super(MessageView, self).get_context_data(**kwargs)
        context['message'] = self.message
        return context

def upmessage(request):
    message_id = None
    if request.method == 'GET':
        message_id = request.GET['message_id']

    data = {"success": True, "likes": 0}
    if message_id:
        message = Message.objects.get(id=int(message_id))
        if message:
            message.like_count += 1
            message.save()
            data["likes"] = message.like_count
        else:
            data["success"] = False
    else:
        data["success"] = False
    return JsonResponse(data)


class NewMessageView(generic.CreateView):
    template_name = 'textform/printMessage.html'
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return resolve_url('textform:detail', self.object.pk)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(NewMessageView, self).form_valid(form)

    def get_initial(self):
        if self.request.method == 'GET':
            if not self.request.user.is_authenticated():
                raise HTTPError


class EditMessageView(generic.UpdateView):
    template_name = 'textform/editMessage.html'
    model = Message
    max_tag_number = 3
    fields = ('title', 'text', 'blog', 'tags')

    def get_queryset(self):
        return Message.objects.filter(author=self.request.user)

    def get_success_url(self):
        return resolve_url('textform:detail', self.object.pk)

    def form_valid(self, form):
        form.instance.author = self.request.user

        return super(EditMessageView, self).form_valid(form)

def deletemessage(request, pk):
    message = get_object_or_404(Message, pk=pk)
    message.published = False
    message.save()
    return HttpResponseRedirect(reverse('textform:index'))

src/templates/textform/detail.html
{% extends "stackoverflow/base.html" %}

{% load widget_tweaks %}
{% load static %}

{% block title %}
    <div class="panel">
        <div class="panel-heading">
            <h4>{{ message.title }} by <a href="#">{{ message.author }}</a></h4>
        </div>
        <div class="panel-body">
          <div class="col-md-1">
            <h1>10</h1>
          </div>
          <div class="col-md-1">
            <button type="button" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-plus"></span></button>
            <button type="button" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-minus"></span></button>
          </div>
          <div class="col-md-2">
            <img class="user-big-icon" src="https://goo.gl/q26Tmc">
          </div>
          <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <p>{{ message.text }} </p>
                </div>
            </div>

          </div>
        </div>
      </div>
{% endblock %}

{% block content %}
    <script>
        function load_comments() {
            $('#comments').load('{% url "textform:comments:comments_ajax" pk=message.id %}');
            return false;
        };
        window.setInterval(load_comments, 1000);
    </script>

    {% if user.is_authenticated %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div class="col-md-12">
            {{ form.text|add_class:"form-control" }}
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12">
            <input type="submit" class="btn btn-primary" value="Add comment">
          </div>
        </div>
    </form>
    {% endif %}

    <div id="comments"></div>
{% endblock %}

{% block sidecont %}
    <div class="sidebar-module search-panel">
        <div class="panel panel-warning">
            <div class="panel-heading">Post info</div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div class="row">
                            <p><b>Blog:</b> <a href="{% url 'textform:blogs:detail' message.blog.id %}">{{ message.blog.name }}</a> </p>
                    </div>

                    <div class="row">
                        <p><b>Comments:</b> {{ message.comment_set.count }}</p>
                    </div>

                    <div class="row">
                        {% if not message.published %}
                            <p><b>State:</b> Not Published</p>
                        {% endif %}
                    </div>

                    <div class="row">
                        <p><b>Published:</b> {{message.pub_date}} </p>
                        <p><b>Last edit:</b> {{ message.mod_date }} </p>
                    </div>

                    <div class="row">
                        {% if  user.is_authenticated %}
                            {% if user == message.author %}
                                <p> <a href="{% url 'textform:editmessage' message.id %}" role="button">Edit message</a>
                                <a href="{% url 'textform:deletemessage' message.id %}" role="button">Delete message</a><p>
                            {% endif %}
                        {% endif %}
                    </div>

                    <div class="row">
                        <span><b>Tags: </b></span>
                        {% for tag in message.tags.all  %}
                             <a href="#" class="panel panel-success">{{ tag }}</a>
                        {% endfor %}
                   </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/templates/textform/editMessage.html
{% extends "stackoverflow/base.html" %}

{% load widget_tweaks %}
{% load static %}



{% block content %}

    <form class="form-horizontal" action="{% url 'textform:editmessage' message.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
        <label class="control-label col-md-1">Title: </label>
        <div class="col-md-9">
            {{ form.title|add_class:"form-control" }}
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-md-1">Text: </label>
        <div class="col-md-9">
            {{ form.text|add_class:"form-control" }}
        </div>
      </div>

      <div class="row col-md-12">
          <div class="col-md-5 form-group">
            <label class="control-label col-md-1">Blog: </label>
            <div class="col-md-9 col-md-offset-1">
                {{ form.blog|add_class:"form-control" }}
            </div>
          </div>

            <script type="text/javascript">
            $(function() {
                $(".chosen-select").chosen({disable_search_threshold: 10});
            });
            </script>

            <div class="col-md-7 form-group">
            <label class="control-label col-md-1">Tags: </label>
            <div class="col-md-9 col-md-offset-1">
                {{ form.tags|add_class:"form-control chosen-select" }}
            </div>
          </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-9">
          <input type="submit" class="btn btn-primary" value="Save">
        </div>
      </div>
    </form>


{% endblock %}

src/templates/textform/index.html
{% extends "stackoverflow/base.html" %}

{% load widget_tweaks %}
{% load static %}

{% block title %}
{%  endblock %}

{%  block content %}
    <h1>Posts</h1>

    <script type="text/javascript">
        $(function() {
            $(".chosen-select").chosen({disable_search_threshold: 10, height: "95%"});
        });
        </script>

    <div class="row">
        <div class="col-md-2">
            <h4>Sort by: </h4>
        </div>
        <form class="col-md-3 input-group">
            {{ form.sort|add_class:"form-control chosen-select" }}
            <span class="input-group-btn">
                <button class="btn btn-sm btn-default" type="submit"><span class="glyphicon glyphicon-ok"></span></button>
            </span>
        </form>
    </div>

    {% if latest_message_list %}
      {% for message in latest_message_list %}

        <div class="panel panel-success">
        <div class="panel-heading">
            <a href="{% url 'textform:detail' message.id %}" active><h4>{{ message.title }}</h4></a>
        </div>

         <script type="text/javascript">
              $(document).on('click', '[data-click-action]', function(source) {
                      console.log(this);
                      var message_id;
                      message_id = $(this).attr("data-message-id");
                      click_url = $(this).attr("data-click-action");
                      $.getJSON(click_url, {message_id: message_id}, function (data) {
                          console.log(data);
                          if(data.success) {
                              $('#like_count').html(data.likes);
                          } else {

                          }
                          return false;
                      });
                      return false;
                  });
          </script>

        <div class="panel-body">
          <div class="col-md-1">
            <h1 id="like_count">{{ message.like_count }}</h1>
          </div>
          <div class="col-md-1">

            <button type="button" data-click-action="/upmessage" data-message-id="{{ message.id }}" class="btn btn-default btn-lg likes-button"><span class="glyphicon glyphicon-plus"></span></button>
            <button type="button" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-minus"></span></button>
          </div>
          <div class="col-md-2">
            <img class="user-big-icon" src="https://goo.gl/q26Tmc">
          </div>
          <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <p><b>Text: </b>{{ message.message_beginning }} <a href="{% url 'textform:detail' message.id %}">More...</a></p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p><b>Blog:</b> <a href="{% url 'textform:blogs:detail' message.blog.id %}">{{ message.blog.name }}</a> </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <p><b>Comments:</b> {{ message.comment_set.count }}</p>
                </div>

                <div class="col-md-8">
                    {% if not message.published %}
                        <p><b>State:</b> Not Published</p>
                    {% endif %}
                </div>
            </div>


            <div class="row">
                <div class="col-md-8 col-md-offset-4">
                    <p><b>Published:</b> {{message.pub_date}} </p>
                    <p><b>Last modified:</b> {{ message.mod_date }} </p>
                </div>
            </div>

          </div>
        </div>
        <div class="row">
            <div class="col-md-1 col-md-offset-1">
                <span><b>Tags: </b></span>
            </div>
            <div class="col-md-10">
                {% for tag in message.tag_set  %}
                     <a href="#" class="panel panel-success">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
      </div>
    {% endfor %}
    {% else %}
        <p>No posts yet.</p>
    {% endif %}
{% endblock %}

{% block sidecont %}
    {% block search %}
    <div class="sidebar-module search-panel">
        <div class="panel panel-warning">
            <div class="panel-heading">Search</div>
            <div class="panel-body">
                <div class="col-md-12">
                    <form class="input-group">
                        {{ form.search|add_class:"form-control"|append_attr:"placeholder:Search posts..." }}
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                        </span>
                    </form><!-- /input-group -->
                  </div><!-- /.col-lg-6 -->
            </div>
        </div>
    </div>
    {% endblock %}

    <div class="sidebar-module">
        <div>
            <div class="panel panel-info">
                <div class="panel-heading">
                    <p>Latest comments:</p>
                </div>
                <ul class="nav nav-sidebar">
                    <div class="list-group">
                        {% if not view.latest_comments %}
                            <div class="col-md-12">
                                <p>No comments yet =(</p>
                            </div>
                        {% endif %}
                        {% for comment in latest_comments %}
                            <div class="list-group-item">
                                <li>
                                    <div>
                                        <p>{{ comment.pub_date }}</p>
                                    </div>
                                    <div>
                                      <p>{{ comment.comment_beginning }} <a href="{% url 'textform:detail' comment.message.id %}">More...</a></p>
                                    </div>
                                    <div>
                                        <a href="#">{{ comment.author }}</a>
                                    </div>
                                </li>
                            </div>
                        {% endfor %}
                </ul>
            </div>
        </div>
    </div>


{% endblock %}

src/templates/textform/printMessage.html
{% extends "stackoverflow/base.html" %}

{% load widget_tweaks %}
{% load static %}


{% block content %}
    <h1>New Post</h1>

    <form class="form-horizontal" action="{% url 'textform:newmessage' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
        <label class="control-label col-md-1">Title: </label>
        <div class="col-md-9">
            {{ form.title|add_class:"form-control" }}
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-md-1">Text: </label>
        <div class="col-md-9">
            {{ form.text|add_class:"form-control" }}
        </div>
      </div>

      <div class="row col-md-12">
          <div class="col-md-5 form-group">
            <label class="control-label col-md-1">Blog: </label>
            <div class="col-md-9 col-md-offset-1">
                {{ form.blog|add_class:"form-control" }}
            </div>
          </div>

            <script type="text/javascript">
            $(function() {
                $(".chosen-select").chosen({disable_search_threshold: 10});
            });
            </script>

            {{ form.tags.errors }}
            <div class="col-md-7 form-group">
            <label class="control-label col-md-1">Tags: </label>
            <div class="col-md-9 col-md-offset-1">
                {{ form.tags|add_class:"form-control chosen-select" }}
            </div>
          </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-9">
          <input type="submit" class="btn btn-primary" value="Post">
        </div>
      </div>
    </form>

{% endblock %}