src/blogs/urls.py
from django.conf.urls import url

from . import views
from django.views import generic

app_name = 'blogs'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.BlogView.as_view(), name='detail'),
]

src/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'
urlpatterns = [
	url(r'^login(?P<next>.+)', views.login, name='login'),
 	url(r'^logout(?P<next>.+)', views.logout, name='logout'),
 	url(r'^register/(?P<next>.+)', views.register, name='register'),
]

src/stackoverflow/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('login.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('textform.urls')),
    url(r'^search/', include('haystack.urls', app_name='search', namespace='search')),
]

src/textform/urls.py
from django.conf.urls import url, include
from . import views
import comments.views
import comments.urls

app_name = 'textform'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^deletemessage/(?P<pk>[0-9]+)$', views.deletemessage, name='deletemessage'),
    url(r'^editmessage/(?P<pk>.+)$', views.EditMessageView.as_view(), name='editmessage'),
    url(r'^newmessage$', views.NewMessageView.as_view(), name='newmessage'),
    url(r'^(?P<pk>[0-9]+)$', views.MessageView.as_view(), name='detail'),
    url(r'^comments/', include('comments.urls', namespace="comments")),
    url(r'^blogs/', include('blogs.urls', namespace="blogs")),
    url(r'^upmessage/$', views.upmessage, name="upmessage"),
]

src/templates/stackoverflow/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    {% load staticfiles %}
    <link href="{% static "css/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    {% load staticfiles %}
    <link href="{% static "css/style.css" %}" rel="stylesheet">

    {% load staticfiles %}
    <script src="{% static "js/manage_likes.js" %}"></script>

</head>
<body role="document">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'textform:index' %}"></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'textform:index' %}">Home</a></li>
                {% if  user.is_authenticated %}
                    <li><a href="{% url 'textform:newmessage'%}">New post</a></li>
                {% endif %}
             </ul>


            <form class="navbar-form navbar-right">
              {% if  user.is_authenticated %}
                    <a href="#" class="btn btn-link" role="button">{{ user.username }}</a>
                    <a href="{% url 'login:logout' request.get_full_path|urlencode %}" type="submit" class="btn btn-default">Sign out</a>
              {% else %}
                  <a href="{% url 'login:login' request.get_full_path|urlencode %}" role = "button" class="btn btn-default">Sign in</a>
                  <a href="{% url 'login:register' request.get_full_path|urlencode %}"  role="button" class="btn btn-default">Register</a>
              {% endif %}
             </form>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% block title %}
                {% endblock %}

                {% block content %}
                {% endblock %}
            </div>

            <div class="col-md-3 col-md-offset-1 blog-sidebar">
                {%  block fast-navig %}
                    <div class="sidebar-module">
                        <div class="btn-group btn-group-justified">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Blogs</button>
                             </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Users</button>
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Help</button>
                            </div>
                        </div>
                    </div>
                {%  endblock %}

                {% block sidecont %}

                {% endblock %}
            </div>
        </div>

    </div>

    {% block footer %}
        <!-- Footer-->
        <div id="footer">
          <div class="container">
            <p class="text-muted">Stackoverflow 2016-2016
              <address class="text-muted">
                <strong>Gainsteva Tatiana: </strong>
                <a href="mailto:#">killmeplease</a>
              </address>
            </p>
          </div>
        </div>
    {% endblock %}


</body>
</html>